global:

  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: rnd
    environment: maa-ml-cam-prod 
    service: prometheus
    region: eu-east-1
    dc: maa-ml-cam

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    scrape_timeout: 30s
    honor_labels: true
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: elasticsearch
    scrape_interval: 30s
    scrape_timeout: 30s
    honor_labels: true
    static_configs:
      - targets: ['elasticsearch-exporter:9114']

  - job_name: pushgateway
    scrape_interval: 30s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
